### ISSUE TITLE
Curly braces linting error

### ISSUE THREAD

**Issue by fcavalieri** [wcandillon/xqlint#51]
![image](https://cloud.githubusercontent.com/assets/4959269/10995286/ee12cbd8-847b-11e5-93d1-b36c41d61af8.png)

on

https://github.com/28msec/cellstore-pro/blob/bd83635b512c53627856221c2dd212e7024295db/queries/modules/io/28/modules/xbrl/import.jq

Removing curly braces around line 135 fixes it

**Comment by wcandillon** [comment]
unfortunately there is not much we can do here. Adding the fn: prefix would
solve the issue too.
