### ISSUE TITLE
Files under Windows

### ISSUE THREAD

**Issue by JonathanRowell** [wcandillon/xqlint#54]
First EXCELLENT Linting.

My files contain text in Unicode (outside ANSI encoding) and on Windows this is a pain if the file does not have a BOM header. Your Lint however does not like these files and complains about the first line.

Second, a wish. I use exist-db and it has it's own database update commands which you give a syntax error. Would it be possible to allow them?

Lastly, a minor point, my files have CRLF (again Windows) and I get a lot of messages when styling. Is there an option to ignore this issue?

And thanks again for your time.

**Comment by wcandillon** [comment]
@JonathanRowell Can you send me an xquery file I can test this on?

Regarding the CRLF warning, do you find the `--style-check` option useful? It's quite experimental. I think  that  `--style-check` is false by default, correct? 

Regarding the existdb syntax, at somepoint I dabbled with the idea to support the syntax here: https://github.com/wcandillon/xqlint/pull/48/files Maybe you could use this as an inspiration to build support for exist-db syntax? You can count on my support to answer question.

**Comment by JonathanRowell** [comment]
[harvester-xql.txt](https://github.com/wcandillon/xqlint/files/60567/harvester-xql.txt)
Sorry for late reply, I was in Germany for a week. I'll test out the option this week. I attach the file with which I tried out your linter.

**Comment by wcandillon** [comment]
@JonathanRowell thanks a lot! Indeed support for non utf-8 files is lacking, I will look into it.

**Comment by wcandillon** [comment]
@JonathanRowell It looks like that unless specified otherwise, UTF-8 is considered to be the default encoding:  https://www.w3.org/TR/xquery-30/#xquery-mime-encoding
I will add support for other encodings if specified in the version declaration.

**Comment by wcandillon** [comment]
@JonathanRowell Could you tell me the encoding of the harvester-xql.txt file? So I can add it to the test suite.

**Comment by JonathanRowell** [comment]
Hi,


I don't understand how it ended with the .txt extension, but it should be utf-8.There might be a BOM at the beginning (3 chars). If this is a problem I'll send you a direct E-Mail with the new file.


regards


Jonathan


________________________________
